"""Centralized constants for the Bike Tour Planner."""

# Routing defaults
DEFAULT_MAX_CONNECTION_DISTANCE_M = 1000.0
DEFAULT_START_SEARCH_RADIUS_KM = 3.0
DEFAULT_TARGET_SEARCH_RADIUS_KM = 10.0
DEFAULT_MAX_CHAIN_LENGTH = 20

# Elevation calculation
ELEVATION_SMOOTHING_WINDOW = 5
ELEVATION_THRESHOLD_M = 3.0
MIN_SEGMENT_LENGTH_POINTS = 10

# Export formatting
ICS_MAX_LINE_LENGTH = 75
PDF_PAGE_WIDTH_CM = 25.0
EXCEL_MAX_LINK_TEXT_LENGTH = 50

# Geocoding
NOMINATIM_USER_AGENT = "booking-gpx-project"
GEOCONTROL_RATELIMIT_SLEEP = 1.0

# Geoapify
GEOAPIFY_DEFAULT_SEARCH_RADIUS_M = 5000
GEOAPIFY_DEFAULT_MAX_POIS = 2
